/***********************************************************************************************************************
 ** Program Filename: makefile
 ** Author: Makenzie Brian
 ** Date: October 9, 2015
 ** Description: makefile for matrix.cpp, war.cpp, and buttercup.cpp
 ** Input: object files?
 ** Output: executable files?
 *******************************************************************************************************************

matrix: matrix.cpp
	g++ matrix.cpp -o matrix

war: war.cpp
	g++ war.cpp -o war

buttercup: buttercup.cpp
	g++ buttercup.cpp -o buttercup

clean:
	rm -f *.o matrix war buttercup
